"""create admin, posts, tags

Revision ID: 0e9026993af2
Revises: c28c1b4dc523
Create Date: 2022-02-04 22:12:21.029135

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e9026993af2'
down_revision = 'c28c1b4dc523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('url_slug', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'posts', ['url_slug'])
    op.alter_column('tag_post_map', 'tag_id',
               existing_type=mysql.CHAR(length=32),
               nullable=True)
    op.alter_column('tag_post_map', 'post_id',
               existing_type=mysql.CHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag_post_map', 'post_id',
               existing_type=mysql.CHAR(length=32),
               nullable=False)
    op.alter_column('tag_post_map', 'tag_id',
               existing_type=mysql.CHAR(length=32),
               nullable=False)
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_column('posts', 'url_slug')
    # ### end Alembic commands ###
