"""empty message

Revision ID: 19cf818b3afc
Revises: 2a38af3ad8c0
Create Date: 2022-02-10 19:35:15.487454

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19cf818b3afc'
down_revision = '2a38af3ad8c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag_post_map', 'tag_id',
               existing_type=mysql.CHAR(length=32),
               nullable=True)
    op.alter_column('tag_post_map', 'post_id',
               existing_type=mysql.CHAR(length=32),
               nullable=True)
    op.drop_constraint('tag_post_map_ibfk_2', 'tag_post_map', type_='foreignkey')
    op.drop_constraint('tag_post_map_ibfk_1', 'tag_post_map', type_='foreignkey')
    op.create_foreign_key(None, 'tag_post_map', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tag_post_map', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag_post_map', type_='foreignkey')
    op.drop_constraint(None, 'tag_post_map', type_='foreignkey')
    op.create_foreign_key('tag_post_map_ibfk_1', 'tag_post_map', 'posts', ['post_id'], ['id'])
    op.create_foreign_key('tag_post_map_ibfk_2', 'tag_post_map', 'tags', ['tag_id'], ['id'])
    op.alter_column('tag_post_map', 'post_id',
               existing_type=mysql.CHAR(length=32),
               nullable=False)
    op.alter_column('tag_post_map', 'tag_id',
               existing_type=mysql.CHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###
