"""empty message

Revision ID: 9624305745f8
Revises: 88c3f4b920bd
Create Date: 2022-02-10 18:08:22.402312

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9624305745f8'
down_revision = '88c3f4b920bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'is_superuser')
    op.alter_column('tag_post_map', 'tag_id',
               existing_type=mysql.CHAR(length=32),
               nullable=True)
    op.alter_column('tag_post_map', 'post_id',
               existing_type=mysql.CHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag_post_map', 'post_id',
               existing_type=mysql.CHAR(length=32),
               nullable=False)
    op.alter_column('tag_post_map', 'tag_id',
               existing_type=mysql.CHAR(length=32),
               nullable=False)
    op.add_column('admins', sa.Column('is_superuser', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
